"use client";
import { FormEvent, useMemo, useState } from "react";

const windows: Record<number, [number, number][]> = { 1: [[12, 18]], 2: [[10, 14], [18, 21]], 3: [[10, 14], [18, 21]], 4: [[10, 14]] };
function pad(n: number) { return String(n).padStart(2, "0"); }
function dates() { const result: { value: string; label: string; day: number }[] = []; const now = new Date(); for (let i = 1; i <= 45; i++) { const d = new Date(now); d.setDate(now.getDate() + i); const day = d.getDay(); if (!windows[day]) continue; const value = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`; result.push({ value, day, label: d.toLocaleDateString("fr-CA", { weekday: "long", day: "numeric", month: "long" }) }); } return result; }
function slots(day: number) { return (windows[day] || []).flatMap(([from, to]) => { const out: string[] = []; for (let minutes = from * 60; minutes < to * 60; minutes += 30) out.push(`${pad(Math.floor(minutes / 60))}:${pad(minutes % 60)}`); return out; }); }
export default function BookingForm() { const availableDates = useMemo(dates, []); const [date, setDate] = useState(availableDates[0]?.value || ""); const selected = availableDates.find((d) => d.value === date); const [done, setDone] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/appointments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); setBusy(false); if (!response.ok) { setError(body.error || "Une erreur est survenue."); return; } setDone(true); }
  if (done) return <div className="booking-success"><span>✓</span><h3>Votre demande est bien reçue.</h3><p>Le partenaire vous contactera sur WhatsApp ou par e-mail pour confirmer le rendez-vous.</p></div>;
  return <form className="booking-form" onSubmit={submit}><div className="booking-form-heading"><span className="opportunity-eyebrow"><span className="opportunity-eyebrow-line" /> RENCONTRE D&apos;INFORMATION</span><h3>Choisissez votre créneau</h3><p>Les horaires sont indiqués en heure de Montréal / Québec.</p></div><div className="booking-grid"><label>Prénom<input name="firstName" required autoComplete="given-name" placeholder="Votre prénom" /></label><label>Nom<input name="lastName" required autoComplete="family-name" placeholder="Votre nom" /></label><label>E-mail<input name="email" required type="email" autoComplete="email" placeholder="vous@exemple.com" /></label><label>WhatsApp<input name="whatsapp" required autoComplete="tel" placeholder="+1 ..." /></label><label>Date<select name="date" required value={date} onChange={(e) => setDate(e.target.value)}>{availableDates.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Heure<select name="time" required>{selected && slots(selected.day).map((time) => <option key={time} value={time}>{time}</option>)}</select></label></div><label className="booking-message">Votre question (facultatif)<textarea name="message" rows={3} placeholder="Ce que vous souhaitez clarifier pendant l’appel..." /></label>{error && <p className="booking-error" role="alert">{error}</p>}<button className="opportunity-button opportunity-button-primary" disabled={busy} type="submit">{busy ? "Enregistrement..." : "Confirmer ma demande"}</button></form>; }
