import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { addAppointment, isAllowedSlot, listAppointments, readSession, updateAppointment } from "@/lib/appointments";

function authorized(token?: string) { const session = readSession(token); return session && ["owner", "partner", "admin"].includes(session.role) ? session : null; }
export async function GET() { const session = authorized((await cookies()).get("finab_session")?.value); if (!session) return NextResponse.json({ error: "Non autorisé" }, { status: 401 }); return NextResponse.json({ appointments: await listAppointments() }); }
export async function POST(request: Request) {
  try { const body = await request.json(); const required = ["firstName", "lastName", "email", "whatsapp", "date", "time"]; if (required.some((key) => typeof body[key] !== "string" || !body[key].trim())) return NextResponse.json({ error: "Veuillez remplir tous les champs obligatoires." }, { status: 400 }); if (!/^\S+@\S+\.\S+$/.test(body.email)) return NextResponse.json({ error: "L’adresse e-mail n’est pas valide." }, { status: 400 }); if (!isAllowedSlot(body.date, body.time)) return NextResponse.json({ error: "Ce créneau n’est pas disponible." }, { status: 400 }); const appointment = await addAppointment({ firstName: body.firstName.trim(), lastName: body.lastName.trim(), email: body.email.trim().toLowerCase(), whatsapp: body.whatsapp.trim(), date: body.date, time: body.time, message: typeof body.message === "string" ? body.message.trim().slice(0, 1000) : "" }); return NextResponse.json({ appointment }, { status: 201 }); } catch { return NextResponse.json({ error: "Impossible d’enregistrer la demande pour le moment." }, { status: 500 }); }
}
export async function PATCH(request: Request) { const session = authorized((await cookies()).get("finab_session")?.value); if (!session) return NextResponse.json({ error: "Non autorisé" }, { status: 401 }); const body = await request.json().catch(() => ({})); if (!body.id || !["new", "confirmed", "completed", "cancelled"].includes(body.status)) return NextResponse.json({ error: "Mise à jour invalide" }, { status: 400 }); const appointment = await updateAppointment(body.id, body.status); return appointment ? NextResponse.json({ appointment }) : NextResponse.json({ error: "Rendez-vous introuvable" }, { status: 404 }); }
