"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import "../admin.css";
type Appointment = { id: string; firstName: string; lastName: string; email: string; whatsapp: string; date: string; time: string; message: string; status: string; createdAt: string };
type User = { id: string; name: string; email: string; phone: string; role: string };
const statusLabels: Record<string, string> = { new: "Nouveau", confirmed: "Confirmé", completed: "Terminé", cancelled: "Annulé" };
export default function AdminDashboard() { const router = useRouter(); const [user, setUser] = useState<User | null>(null); const [appointments, setAppointments] = useState<Appointment[]>([]); const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(""); const [showCreate, setShowCreate] = useState(false);
 async function load() { const me = await fetch("/api/auth/me"); if (!me.ok) { router.replace("/admin"); return; } const meData = await me.json(); setUser(meData.user); const [a, u] = await Promise.all([fetch("/api/appointments"), fetch("/api/admin/users")]); if (a.ok) setAppointments((await a.json()).appointments); if (u.ok) setUsers((await u.json()).users); }
 useEffect(() => { load(); }, []);
 async function update(id: string, status: string) { await fetch("/api/appointments", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); load(); }
 async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.replace("/admin"); }
 async function create(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); const r = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))) }); const data = await r.json(); if (!r.ok) { setError(data.error); return; } setShowCreate(false); load(); }
 return <main className="dashboard-shell"><header className="dashboard-header"><div><span className="admin-kicker">FINAB · ESPACE PARTENAIRE</span><h1>Bonjour {user?.name || ""}</h1></div><button className="admin-ghost-button" onClick={logout}>Se déconnecter</button></header><section className="dashboard-stats"><div><span>Demandes reçues</span><strong>{appointments.length}</strong></div><div><span>Nouveaux rendez-vous</span><strong>{appointments.filter((a) => a.status === "new").length}</strong></div><div><span>Confirmés</span><strong>{appointments.filter((a) => a.status === "confirmed").length}</strong></div><div><span>Accès utilisateurs</span><strong>{users.length}</strong></div></section><section className="dashboard-panel"><div className="dashboard-panel-title"><div><span className="admin-kicker">AGENDA</span><h2>Les rendez-vous</h2></div><button onClick={() => load()}>Actualiser</button></div>{appointments.length === 0 ? <p className="dashboard-empty">Aucune demande reçue pour le moment.</p> : <div className="appointment-table"><div className="appointment-row appointment-head"><span>Personne</span><span>Créneau</span><span>Contact</span><span>Statut</span><span>Action</span></div>{appointments.map((a) => <div className="appointment-row" key={a.id}><span><strong>{a.firstName} {a.lastName}</strong><small>{a.message || "Aucune question"}</small></span><span>{new Date(`${a.date}T12:00:00`).toLocaleDateString("fr-CA", { weekday: "short", day: "numeric", month: "short" })}<strong>{a.time} · Montréal</strong></span><span><a href={`mailto:${a.email}`}>{a.email}</a><small>{a.whatsapp}</small></span><span><select value={a.status} onChange={(e) => update(a.id, e.target.value)}>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></span><span><button className="row-action" onClick={() => update(a.id, "confirmed")}>Confirmer</button></span></div>)}</div>}</section>{user?.role === "owner" && <section className="dashboard-panel"><div className="dashboard-panel-title"><div><span className="admin-kicker">ACCÈS</span><h2>Utilisateurs</h2></div><button onClick={() => setShowCreate(!showCreate)}>+ Créer un accès</button></div>{showCreate && <form className="create-user-form" onSubmit={create}><input name="name" required placeholder="Nom complet" /><input name="email" required type="email" placeholder="E-mail" /><input name="phone" placeholder="WhatsApp" /><input name="password" required minLength={10} placeholder="Mot de passe (10 caractères min.)" /><select name="role" defaultValue="partner"><option value="partner">Partenaire</option><option value="admin">Administrateur</option></select><button type="submit">Créer</button>{error && <small className="admin-error">{error}</small>}</form>}<div className="user-list">{users.map((item) => <div key={item.id}><strong>{item.name}</strong><span>{item.email} · {item.role}</span></div>)}</div></section>}</main>; }
